;Name of the Action
name=make
;Path of the binary. e.g. gcc or /usr/bin/gcc, if the binary is in the path, it is automaticly resolved
bin=make
 ;Full argv Struct (program name + args), e.g. "gcc -o hello hello.c"
args=make